### ISSUE TITLE
Missing the COPYING and author files

### ISSUE THREAD

**Issue by vanicat** [magit/with-editor#1]
Hello,

While making the Debian package for with-editor, it appear that this package lack its copy of the GPL, when the copyright say that a copy of the GPL should be there.

Also, the copyright is given to the "The Magit Project Contributors", but there is no list of those. I've run `git log -- lisp/with-editor.el | grep Author | sort  -u`, and found the following list of author:

     Barak A. Pearlmutter <barak+git@pearlmutter.net>
     Jonas Bernoulli <jonas@bernoul.li>
     Lele Gaifax <lele@metapensiero.it>
     Noam Postavsky <npostavs@users.sourceforge.net>
     Rémi Vanicat <vanicat@debian.org>

Thanks.

**Comment by tarsius** [comment]
> it appear that this package lack its copy of the GPL, when the copyright say that a copy of the GPL should be there.

Which is why I usually change that paragraph in my little one library packages to:

```
;; For a full copy of the GNU General Public License
;; see <http://www.gnu.org/licenses/>.
```

I think that from a legal standpoint this is okay because even the FSF does not include a copy of the GPL for the one-file packages it distributes on ELPA (they would not be one-file packages anymore otherwise).

> "The Magit Project Contributors"

The intention behind that phrasing is "Everyone who contributed still holds their copyright. No copyright has been assigned to the maintainers or anybody else". But since it's not that simple to get ones hand on the list of those contributors, that isn't good enough. (But have a look at the "reincarnation commit", it does contain a pre-rebirth list of contributors.)

So I have now added the COPYING and AUTHORS.md files. I'll probably create a subminor commit in a week or two. If not feel free to ping me.
