### ISSUE TITLE
EDITOR  setting in vterm breaks remote programs calling EDITOR 

### ISSUE THREAD

**Issue by Thaodan** [magit/with-editor#117]
# What behavior you expected
The setting should either work or be skipped for remote connection.
# What behavior you observed
Opening a vterm buffer for a remote connections such as tramp breaks programs that want to call $EDITOR.

# How we can reproduce the issue.
1. Open a file with tramp
2. M-x `vterm` RET
3. `echo $EDITOR`

**Comment by tarsius** [comment]
This very likely will end up as a `wontfix`.

I tried to resist teaching `with-editor` to support use-cases other than those of Magit, but unfortunately a user persuaded me that doing it would not be much work beyond the time needed for the initial implementation. That assessment turned out to be very wrong, and I am getting to the point where I don't want to suffer anymore the consequences of not having pushed back harder, when I still had the chance.

I recommend you just don't use any of `with-editor`'s "augmentation" features. They are not actually needed! A very viable alternative is to just set `$EDITOR` properly in your shells init file.

**Comment by Thaodan** [comment]
> I tried to resist teaching `with-editor` to support use-cases other than those of Magit, but unfortunately a user persuaded me that doing it would not be much work beyond the time needed for the initial implementation. That assessment turned out to be very wrong, and I am getting to the point where I don't want to suffer anymore the consequences of not having pushed back harder, when I still had the chance.

Understandable, thanks for explaining!
