### ISSUE TITLE
Can't call emacsclient.exe on Windows

### ISSUE THREAD

**Issue by TheRealMintd** [magit/with-editor#121]
When using Magit on Windows, commits can't be created due to the path not being properly escaped when calling the emacsclient executable.

These lines appear in the `magit-process` buffer:

```
  1 git.exe … "commit" "--"
c:/Program\ Files\ (x86)/censor/emacs-master/bin/emacsclient.exe: -c: line 1: syntax error near unexpected token `x86'
c:/Program\ Files\ (x86)/censor/emacs-master/bin/emacsclient.exe: -c: line 1: `c:/Program\ Files\ (x86)/censor/emacs-master/bin/emacsclient.exe "$@"'
```

Running `(replace-regexp-in-string "\s" "\\\\\\&" with-editor-emacsclient-executable)` gives this output: `"c:/Program\\ Files\\ (x86)/censor/emacs-master/bin/emacsclient.exe"`
Running `(shell-quote-argument with-editor-emacsclient-executable)` gives this output: `"\"c:/Program Files (x86)/censor/emacs-master/bin/emacsclient.exe\""`

Reverting 84ba06ed513e97223630905f4788370e18116f40 fixes the issue for me.

**Comment by tarsius** [comment]
#119 vs. #121

**Comment by tarsius** [comment]
Obviously I didn't think about it enough, before I "fixed" #119.

`/path to/editor` and `emacsclient -nw` are both valid editors.  Obviously one of the spaces must be quoted while the other must not. Different tools might use different quoting rules internally, depending on the used language and their own conventions, but `$EDITOR` is a feature that has to work regardless of those differences, so using posix shell quoting is the obvious choice.

`git` expects shell quoting. It breaks if merely spaces are quoted but, e.g., parens are not.

I have a bit of dejavu, it feels like I have come to the same conclusion before. But couldn't quickly find any past discussion about it, so now I made sure to add a code comment.

`pass` (this is what #119 is about) invokes the editor like so: `${EDITOR:-vi} "$tmp_file"`. This is wrong, it should use `eval ${EDITOR:-vi} "$tmp_file"`. Without doing that, it does not work for all valid `$EDITOR`s.

If you want to experiment yourself, here's some code (obviously you'll have to adjust some paths):

`use-editor`:

```shell
#!/run/current-system/profile/bin/env bash

# bad:
#$EDITOR /tmp/testfile
#"$EDITOR" /tmp/testfile
# correct:
eval "$EDITOR" "/tmp/testfile"
```

`editor`, `ed itor`, `ed (itor)` and `ed@itor`:

```shell
#!/run/current-system/profile/bin/env bash
echo test > $1
```

`test-editor.el`:

```emacs-lisp
(let* (;;(e "/home/jonas/opt/bin/editor")
       (e "/home/jonas/opt/bin/ed itor")
       ;;(e "/home/jonas/opt/bin/ed (itor)")
       ;;(e "/home/jonas/opt/bin/ed@itor")
       ;;(e "/home/jonas/opt/bin/emacsclient")
       (process-environment
        (cons (concat "EDITOR="
                      ;;e
                      (shell-quote-argument e)
		      ;;(shell-quote-argument e) " --create-frame"
                      ;;(replace-regexp-in-string "\s" "\\\\\\&" e)
                      )
              process-environment)))
  ;;(start-process "" (current-buffer) "git" "commit" "--allow-empty")
  (start-process "" (current-buffer) "~/opt/bin/use-editor")
  )
```

**Comment by TheRealMintd** [comment]
Thanks for fixing the issue! Looks like I've learned something today, I don't think I've ever seen `eval "$EDITOR"` before.

**Comment by tarsius** [comment]
Note though that I did not find an authoritative source on the matter or at least some plausible sounding blog post. (Search engines have gotten so bad that I wasn't able to find anything that even remotely addressed my queries. Instead I got a long list of resources that are helpful for people who don't understand how environment variables work in the first place.)

So this is all based on educated guesses, experiments and some reasoning about the results.

**Comment by mentalisttraceur** [comment]
For what it's worth, there are programs out there that do the equivalent of `"$EDITOR"` instead of `eval "$EDITOR"`. If you search for "how to pass arguments in $EDITOR", common advice is to write a script file and point `EDITOR` at it. Given that the latter basically immortalizes Bourne-like shell behavior as the API which users will expect not to break, I would never have written a tool that used `EDITOR` as anything other than an executable file's name or path.

So it's not at all clear to me that `git` is even remotely "in the right" for interpreting `EDITOR` how it does. However, `git` is wide-spread enough, and makes up such a large share of `EDITOR` environment variable usage, that Git's choices here might be effectively pushing the world towards a new standard, even if it's for the worse from an architecture/design perspective.

Having said all that, instead of relying on the interpretation of `EDITOR`, your `with-editor` Emacs package can ship with a script - let's say you call it `with-editor.sh` and have it install alongside your elisp files: then you could set `EDITOR` to the absolute path of that script. For remote and as-a-different-user editing through TRAMP, you could have Emacs write that script to a temporary location first (note that it is crucial for security reasons that the temporary file used by a given user cannot be written or replaced or preemptively created by any other user - otherwise using `EDITOR` after a TRAMP with `sudo::` would become a privilege escalation vulnerability just waiting to be exploited).

**Comment by tarsius** [comment]
> Having said all that, instead of relying on the interpretation of `EDITOR`, your `with-editor` Emacs package can ship with a script - let's say you call it `with-editor.sh` and have it install alongside your elisp files: then you could set `EDITOR` to the absolute path of that script. For remote and as-a-different-user editing through TRAMP, you could have Emacs write that script to a temporary location first (note that it is crucial for security reasons that the temporary file used by a given user cannot be written or replaced or preemptively created by any other user - otherwise using `EDITOR` after a TRAMP with `sudo::` would become a privilege escalation vulnerability just waiting to be exploited).

I don't intend to do that. I wrote this package for the benefit of `git commit` and someone convinced me to generalize it to be generally useful, even though I knew that would result in a huge amount of work for me. I don't want to repeat that mistake. What we have now works fairly well, requiring a script that has to be copied to remote machines is an additional thing that can, and will, go wrong.

**Comment by mentalisttraceur** [comment]
> I don't want to repeat that mistake.

That's totally fair, though I think that suggests maybe you should just intern a copy of this code into `magit`, and maybe maintaining an external `with-editor` package is a game you would rather stop playing (I'm sure someone would eventually step up to maintain it).

> What we have now works fairly well

How broadly/generally well? How many other programs run the value of `EDITOR` through a shell's evaluation, versus just shoving it into `execvp` or similar? Maybe I'm wrong about how common the practice is, but until I saw how `with-editor` worked I would've expected that *none* of them do, except sometimes by accident (due to running it through `system` without considering the ramifications of shell interpretation).

**Comment by darkfeline** [comment]
I wanted to add some additional info on this bug, since my search about `EDITOR` handling led me here.

I checked Bash (which I think is as good as a de facto standard), and it does what is equivalent to this:

```
eval "$EDITOR" "/tmp/testfile"
```

(Note that this is subtly different from `$EDITOR "/tmp/testfile"`)

You can test this by running in Bash:

```
$ VISUAL="echo hi; vi"
```

and then using the `CTRL-X CTRL-E` binding in Bash to edit a command in your editor.

(I admit I was also surprised by this, I have always assumed it would be `"$EDITOR" "/tmp/testfile"`)
