### ISSUE TITLE
[BUG] make-process--with-editor-process-filter: Creating pipe: Too many open files

### ISSUE THREAD

**Issue by ieure** [magit/with-editor#122]
I noticed recently that shell sessions would go completely wild and trigger a process filter error for every line of output.  Looking in `*Messages*`, I see:

```
error in process filter: Creating pipe: Too many open files
error in process filter: make-process--with-editor-process-filter: Creating pipe: Too many open files
```

It's easy to reproduce:

1. Install and activate `with-editor`.
2. Type `M-x shell RET` to open a `*shell*` buffer.
3. Output a lot of text.  Examples:
   - `find /`
   - `cat $(find /usr/share/doc -name README* -not -name \*gz); zcat $(find /usr/share/doc -name README*gz)`
   - `cat $(find /usr/include -type f -name \*.h)`
4. Observe that Emacs becomes unresponsive because of the process filter error, making it impossible to kill the process generating the output, which causes the error.

I have no special with-editor configuration.  I'm on 3.2.0, commit 4da1097.

**Comment by ieure** [comment]
Adding: My computer is running Debian 11.6 "bullseye."  I'm on GNU Emacs 28.2, but I've reproduced on 29.x and 30.x snapshots as well.

**Comment by tarsius** [comment]
Hm, I have some vague memory of that happening too me to for a while, quite some time ago. Unfortunately I don't remember what the issue was; I just have some even more vague memory of it not being the fault of some package, but the result of a user error. I think I also observed this with `with-editor`/`magit`, but believe the correlation was just due to Magit starting a lot of processes.

**Comment by tarsius** [comment]
I don't think it was a configuration error at the emacs or magit level, so you'll probably get better results if you search just for the error message, without mentioning emacs, magit or with-editor.

**Comment by ieure** [comment]
> I don't think it was a configuration error at the emacs or magit level, so you'll probably get better results if you search just for the error message, without mentioning emacs, magit or with-editor.

I know how to increase the number of file descriptors.  The problem is not the FD limit, but that `make-process--with-editor-process-filter` [is applied to *every process*](https://github.com/magit/with-editor/blob/59867aebe16454be4d8c0c858f3b00b8a34f3f61/lisp/with-editor.el#L582-L583), regardless of whether I'm using with-editor to edit a file or not.  The process filter does something (I don't know what) which causes FDs to be opened rapidly when it filters a lot of output, which exhausts the limit.  The problem is that the filter is active even when I'm not doing anything related to `with-editor` at all.  Even if I jacked my FD limit sky-high, it would be doing unnecessary work and slowing my Emacs session, which is not ideal.

The problem is not reproduceable with `emacs -Q`.  Activating `with-editor` reproduces the problem 100% of the time with the steps I've given.  It is a with-editor bug, and one that wrecks my Emacs sessions with distressing regularity.

**Comment by tarsius** [comment]
> I know how to increase the number of file descriptors.

Sorry for suggesting otherwise. That was solely based on the face that *I* would have to do so because I don't remember the details.

> The problem is [...] that make-process--with-editor-process-filter [is applied to every process](https://github.com/magit/with-editor/blob/59867aebe16454be4d8c0c858f3b00b8a34f3f61/lisp/with-editor.el#L582-L583), regardless of whether I'm using with-editor to edit a file or not.

But outside of the `with-editor` macro (and similar), this advice does very little. Elsewhere `with-editor--envvar` should always be `nil`.

```elisp
(cl-defun make-process--with-editor-process-filter
    (fn &rest keys &key name buffer command coding noquery stop
        connection-type filter sentinel stderr file-handler
        &allow-other-keys)
  (if (or (not file-handler) (not with-editor--envvar))
      (apply fn keys)
    ...))
```

Is `with-editor--envvar` not `nil` for you? If so, we have to figure out where the non-nil value escapes.

**Comment by tarsius** [comment]
I've just remembered what the problem was in my case. It had nothing to do with this package.

I also think your problem has nothing to do with this package. You couldn't find anything in `make-process--with-editor-process-filter` that consume file descriptors and I didn't spot anything either. Furthermore all it does for processes started outside of `with-editor` et al. is essentially `(and (or (not often-nil) (not this-is-nil)) (apply would-be-called-anyway keys)`.
