### ISSUE TITLE
proper way to use with-editor with minor mode active in opened buffer?

### ISSUE THREAD

**Issue by wbolster** [magit/with-editor#23]
when i use `(with-editor-async-shell-command ...)` to spawn a command that opens an editor, a new emacs buffer opens, which is great. however, `with-editor-mode` is not enabled in that buffer, so the remaps from `with-editor-mode-map` are not active, which means it is hard to close the buffer in the proper way, since `with-editor-finish` or `...-cancel` are not bound to any (standard) keys.

am i missing something?

**Comment by wbolster** [comment]
i noticed that `magit` calls `(with-editor-mode 1)` explicitly, but this does not really work for the common case where it is completely unknown which file (and hence which major mode) will be opened.

would it be possible for `with-editor` to enable the mode automatically?

**Comment by tarsius** [comment]
The problem is that `server.el`, and any code hooking into it, cannot know whether `with-editor` was involved in the creation of the `emacsclient` instance that is making an edit request.

We might some heuristics, but I don't think there's anything that would always get it right. So I don't want to go down that road. The only approach that I can think of that has the potential of always working is to check whether  the `emacsclient` is a child process, or a process that in turn is a child process of the current `emacs` instance, and we have recorded that that process was started with `with-editor` in effect.

Another approach could be to add a variant of `with-editor-mode` that only adds the `C-c C-c` and `C-c C-k` bindings, but unlike in `with-editor-mode-map` does not remap any of the standard key bindings. But even then, I don't think this should be enabled by default. Instead there should be a globalized mode, which has the local mode enable by using one of `server-{visit,switch}-hook` (or if that won't work by advising the appropriate function from `server.el`).

**Comment by wbolster** [comment]
thanks for the reply.

would it be an idea to set `$EDITOR` to something with arguments which can somehow be detected by the server process.

having args in `$EDITOR` instead of just the name of an executable seems to work fine for at least `git commit` and `direnv edit`:

```
$ export EDITOR='vim -e'
$ git commit
... editor opens, use :q to quit
```

or perhaps a dedicated server with its own socket address which the server process recognizes as being a with-editor server?

(just thinking out loud.)

**Comment by monnier** [comment]
Note that `server.el` receives the environment of the `emacsclient` process, so if we add an `INSIDE_EMACS_WITH_EDITOR=yes` environment var to the subprocess, we should be able to distinguish those emacsclients run from within `with-editor` from others, tho it'll probably require some advising of server.el functions.

**Comment by wbolster** [comment]
i am not sure the environment is sent. i debugged this a bit earlier, and iirc those are only sent when `emacsclient --create-frame` (or `-c`) is used.

**Comment by tarsius** [comment]
> if we add an `INSIDE_EMACS_WITH_EDITOR=yes` environment var to the subprocess, we should be able to distinguish those emacsclients run from within `with-editor` from others

https://github.com/magit/with-editor/compare/enable-mode-emacsclient?expand=1

> [environment variables] are only sent when `emacsclient --create-frame` (or `-c`) is used.

Unfortunately that's true. Fortunately fixing it is likely as easy as:

```diff
diff --git a/lib-src/emacsclient.c b/lib-src/emacsclient.c
index c22b308afd..f7be5ce4f6 100644
--- a/lib-src/emacsclient.c
+++ b/lib-src/emacsclient.c
@@ -1654,15 +1654,12 @@ main (int argc, char **argv)
 #endif /* HAVE_NTGUI */
 
   /* Send over our environment and current directory. */
-  if (!current_frame)
+  int i;
+  for (i = 0; environ[i]; i++)
     {
-      int i;
-      for (i = 0; environ[i]; i++)
-        {
-          send_to_emacs (emacs_socket, "-env ");
-          quote_argument (emacs_socket, environ[i]);
-          send_to_emacs (emacs_socket, " ");
-        }
+      send_to_emacs (emacs_socket, "-env ");
+      quote_argument (emacs_socket, environ[i]);
+      send_to_emacs (emacs_socket, " ");
     }
   send_to_emacs (emacs_socket, "-dir ");
   quote_argument (emacs_socket, cwd);
```

For now I am using another approach: use the sleeping editor instead of the emacsclient.

https://github.com/magit/with-editor/compare/enable-mode?expand=1

**Comment by tarsius** [comment]
I'm afraid I had to reintroduce this issue because of #40. But you can revert that in turn by setting the new option `with-editor-shell-command-use-emacsclient` to `nil`.

**Comment by wbolster** [comment]
thanks for the heads up @tarsius.

can i `let`-bind `with-editor-shell-command-use-emacsclient` and call a `with-editor-shell-command` function inside that `(let ...)` or is that the wrong approach?

**Comment by tarsius** [comment]
That should work, I think.
