### ISSUE TITLE
disable the focus grabbing behavior of with-editor

### ISSUE THREAD

**Issue by amosbird** [magit/with-editor#49]
Hi, when executing magit-status and quickly focus out emacs, after the magit buffer pops up, emacs grabs the focus back. This is quite inconvenient. Is there a way to prevent that focus changing? Thanks!

**Comment by tarsius** [comment]
Magit only uses `with-editor` when it needs the user to edit a commit message or a list of commits to be rebased.

I saw your similar question on Gitter and did not answer it because you did not provide enough information for me to do so.

You should always begin by consulting the documentation. Then you should try to produce the issue using `emacs -Q`. [Here](https://magit.vc/manual/magit/Debugging-Tools.html) you can learn how to do that if you have installed Magit using `package.el`. You might also want to read [this blog post](https://swsnr.de/posts/reproduce-bugs-in-emacs-q), which explains why package maintainers ask you do that.

Once you have done the necessary research, you should ask your question on the [Emacs Stackexchange](https://emacs.stackexchange.com/). That usually works better, not least because unlike in a chat, that site encourages those who need help to do their part by describing the issue in more depth, which in turn encourages them to do some research on their own first. That makes it easier to help. Also the conversations that happen there are searchable, so helping one user might actually help many. That makes it more rewarding to help.

**Comment by amosbird** [comment]
@tarsius Thanks for the guideline. I've posted the question with reproduce steps and env on [Emacs Stackexchange](https://emacs.stackexchange.com/questions/39426/how-can-i-prevent-magit-status-command-from-grabbing-the-frame-focus)
