### ISSUE TITLE
Add "proper" with-editor wrappers for shell command (term, ansi-term, eshell, etc...)

### ISSUE THREAD

**Issue by darkfeline** [magit/with-editor#57]
with-editor 2.7.4

The `process-send-string` in `with-editor-export-editor` causes the shell prompt to be printed twice.

Furthermore, point is left after the first prompt, before the read-only second prompt, so `C-e` is needed before typing anything.

**Comment by darkfeline** [comment]
Actually, I don't know.  `with-editor-export-editor` interacts oddly with both `ansi-color.el` and `xterm-color.el`, and I'm not entirely sure what's going on.  Some of it appears to be a race condition, since putting `(debug)` in `with-editor-export-editor` before and after the `process-send-string` yields different behavior.

I will reopen if I have something more concrete.

**Comment by darkfeline** [comment]
I'm tentatively reopening this.  I don't know for the life of me what's causing me pain with `with-editor-export-editor` and `xterm-color.el`, but adding a thin wrapper like

```
(defun my-shell ()
  (interactive)
  (with-editor
    (call-interactively #'shell)))
```

works much more reliably.  Does it make sense to add this kind of wrapper to `with-editor`?

(The actual problem I encountered was that the `(while (accept-process-output process 0.1))` line in `with-editor-export-editor` causes the first instance of the shell prompt to not be fontified correctly by `xterm-color.el`.  Removing the `while` or replacing it with something like `(accept-process-output process 0.01)` fixes the problem, but using a larger value like `(accept-process-output process 0.05)` causes the problem.  There's clearly some kind of race, but hell if I know what.)

**Comment by tarsius** [comment]
This is probably related to 73d3d1ac1470001e184a5ead88f770eeb71a5461 and/or the issues mentioned there. In particular the statement at the end of https://github.com/magit/with-editor/issues/23#issuecomment-331728323 seems relevant. I.e. I am aware that there are some timing issues, but I was still knee-deep in this code I was not able to fix it (possibly because there is no fix) and now that I haven't looked at this code in a long time I am probably even less likely to come up with a satisfying solution.

I don't really want to add a wrapper as you have proposed, but if that works for you, then I see no reason why you shouldn't use that.

**Comment by darkfeline** [comment]
Got it, thanks
